# -- Main Menu --

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "小册"
  weight = 15

[[main]]
  name = "NestJS"
  parent = "小册"
  pageRef = "nestjs"
  weight = 10

[[main]]
  name = "Vite"
  parent = "小册"
  pageRef = "vite"
  weight = 20

[[main]]
  name = "Vue3"
  parent = "小册"
  pageRef = "vue3"
  weight = 30

[[main]]
  name = "TypeScript"
  parent = "小册"
  pageRef = "typescript"
  weight = 40

[[main]]
  name = "TS 类型体操"
  parent = "小册"
  pageRef = "ts-type-gymnastics"
  weight = 50

[[main]]
  name = "基于 Vite 的组件库工程化实战"
  parent = "小册"
  pageRef = "vite-component-library"
  weight = 60

[[main]]
  name = "前端性能优化"
  parent = "小册"
  pageRef = "performance"
  weight = 70

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/BINGWU2003"
  weight = 200

[[main]]
  identifier = "blowfish"
  pre = "globe"
  url = "https://blowfish.page"
  weight = 210

# -- Footer Menu --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10
